// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:411680924938:web:d1b488e78317d6d0b786f3',
    messagingSenderId: '411680924938',
    projectId: 'gp-app-c24de',
    authDomain: 'gp-app-c24de.firebaseapp.com',
    storageBucket: 'gp-app-c24de.firebasestorage.app',
    measurementId: 'G-TSES0L43GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:411680924938:android:d9455e7c31544e60b786f3',
    messagingSenderId: '411680924938',
    projectId: 'gp-app-c24de',
    storageBucket: 'gp-app-c24de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:411680924938:ios:2bcf4a15f8df1bcfb786f3',
    messagingSenderId: '411680924938',
    projectId: 'gp-app-c24de',
    storageBucket: 'gp-app-c24de.firebasestorage.app',
    iosBundleId: 'com.example.gpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:411680924938:ios:2bcf4a15f8df1bcfb786f3',
    messagingSenderId: '411680924938',
    projectId: 'gp-app-c24de',
    storageBucket: 'gp-app-c24de.firebasestorage.app',
    iosBundleId: 'com.example.gpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:411680924938:web:168fb589e8152b44b786f3',
    messagingSenderId: '411680924938',
    projectId: 'gp-app-c24de',
    authDomain: 'gp-app-c24de.firebaseapp.com',
    storageBucket: 'gp-app-c24de.firebasestorage.app',
    measurementId: 'G-MJLXRFPJEQ',
  );
}
