import 'package:flutter/material.dart';

// This is a compatibility wrapper that maintains the existing
// AppLocalizations.of(context)!.get('key') API while using ARB-generated
// translations under the hood. This avoids changing every single screen.

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // ── All translations in a static map ──────────────────────────────────────
  // This is populated from ARB content at compile time.
  // We keep the map approach for the `get()` convenience method.
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'HealthSync',
      'getStarted': 'Get Started',
      'onboardingTitle': 'Your Health, Your Hands',
      'onboardingSubtitle':
          'Monitor your vitals, manage your records, and connect with doctors easily.',
      'login': 'Login',
      'createAccount': 'Create Account',
      'accessAccount': 'Access your HealthSync account',
      'emailAddress': 'Email Address',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'medicalLicense': 'Medical License Number',
      'forgotPassword': 'Forgot Password?',
      'orLoginWith': 'Or login with',
      'or': 'OR',
      'continueWithGoogle': 'Continue with Google',
      'processingLogin': 'Processing Login...',
      'creatingAccount': 'Creating Account...',
      'patient': 'Patient',
      'doctor': 'Doctor',
      'enterEmail': 'Please enter your email',
      'validEmail': 'Please enter a valid email',
      'enterPassword': 'Please enter your password',
      'passwordLength': 'Password must be at least 6 characters',
      'passwordLength8': 'Password must be at least 8 characters',
      'confirmPasswordReq': 'Please confirm your password',
      'passwordsNoMatch': 'Passwords do not match',
      'enterName': 'Please enter your full name',
      'enterLicense': 'Please enter license number',
      'resetPassword': 'Reset Password',
      'resetPasswordDesc':
          'Enter your email address and we\'ll send you a link to reset your password.',
      'sendResetLink': 'Send Reset Link',
      'hello': 'Hello',
      'dashboard': 'Dashboard',
      'vitals': 'Vitals',
      'assistant': 'Assistant',
      'profile': 'Profile',
      'myProfile': 'My Profile',
      'currentHealthStatus': 'Current Health Status',
      'normal': 'Normal',
      'warning': 'Warning',
      'critical': 'Critical',
      'heartRate': 'Heart Rate',
      'bloodOxygen': 'Blood Oxygen',
      'bloodPressure': 'BP (Est)',
      'nextFollowUp': 'Next Follow-up',
      'seeAll': 'See All',
      'vitalsComingSoon': 'Vitals History (Coming Soon)',
      'view': 'View',
      'needAttention': 'Need Attention',
      'criticalAlert': 'Critical Alert',
      'patientsNeedAttention': 'patient(s) need immediate attention',
      'settings': 'Settings',
      'medicalHistory': 'Medical History',
      'privacySecurity': 'Privacy & Security',
      'helpSupport': 'Help & Support',
      'guestUser': 'Guest User',
      'noEmail': 'No Email',
      'notifications': 'Notifications',
      'notificationsDesc': 'Receive alerts and reminders',
      'language': 'Language',
      'logout': 'Logout',
      'logoutConfirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'notificationsTitle': 'Notifications',
      'noNotifications': 'No new notifications',
      'markAllRead': 'Mark all as read',
      'doctorChatTitle': 'Chat with Dr. Sarah',
      'typeDoctorMessage': 'Write your message...',
      'doctorResponse':
          'Hello! I received your message. I will check your vitals and get back to you shortly.',
      'chat': 'Chat',
      'doctorDashboard': 'Doctor Dashboard',
      'myPatients': 'My Patients',
      'totalPatients': 'Total Patients',
      'pendingMessages': 'Pending Messages',
      'todayAppointments': "Today's Appointments",
      'recentPatients': 'Recent Patients',
      'searchPatients': 'Search patients...',
      'viewPatient': 'View Patient',
      'sendMessage': 'Send Message',
      'patientDetails': 'Patient Details',
      'lastUpdate': 'Last Update',
      'typePatientMessage': 'Write a message to patient...',
      'vitalsHistory': 'Vitals History',
      'assignPatient': 'Assign Patient',
      'searchByNameOrPhone': 'Search by name or phone number...',
      'searchByNameLabel': 'By Name',
      'searchByPhoneLabel': 'By Phone',
      'searchByNameHint': 'Enter patient name...',
      'searchByPhoneHint': 'Enter phone number...',
      'assign': 'Assign',
      'noResults': 'No patients found',
      'patientAssigned': 'Patient assigned successfully!',
      'alreadyAssigned': 'Patient is already assigned to you',
      'connectionError':
          'Connection error. Please check your internet and try again.',
      'serverError': 'Server error. Please try again later.',
      'unexpectedError': 'Something went wrong. Please try again.',
      'phone': 'Phone',
      'retry': 'Retry',
      'searching': 'Searching...',
      'typeToSearch': 'Type a name or phone number to search',
      'removePatient': 'Remove Patient',
      'removePatientConfirm':
          'Are you sure you want to remove this patient from your list?',
      'removePatientSuccess': 'Patient removed successfully',
      'removePatientError': 'Failed to remove patient. Please try again.',
      'remove': 'Remove',
      'conditions': 'Conditions',
      'medications': 'Medications',
      'allergies': 'Allergies',
      'procedures': 'Procedures',
      'diagnosed': 'Diagnosed',
      'dosage': 'Dosage',
      'frequency': 'Frequency',
      'since': 'Since',
      'active': 'Active',
      'ongoing': 'Ongoing',
      'controlled': 'Controlled',
      'seasonal': 'Seasonal',
      'asNeeded': 'As needed',
      'severe': 'Severe',
      'mild': 'Mild',
      'allergen': 'Allergen',
      'reaction': 'Reaction',
      'assistantTitle': 'HealthSync Assistant',
      'typeMessage': 'Describe your symptoms...',
      'urgentWarning': 'Urgent: Call emergency services now',
      'welcomeMessage':
          'Hello! I\'m the HealthSync assistant. How can I help you today?',
      'emergencyResponse':
          'Based on your symptoms, this could be serious. Please refer to the emergency banner above.',
      'generalResponse': 'I understand. Can you tell me more?',
      'success': 'Success!',
      'error': 'Error!',
      'info': 'Info',
      'drSarahJohnson': 'Dr. Sarah Johnson',
      'drAhmedHassan': 'Dr. Ahmed Hassan',
      'drSaraMohamed': 'Dr. Sara Mohamed',
      'drOmarAli': 'Dr. Omar Ali',
      'drFatimaYoussef': 'Dr. Fatima Youssef',
      'appointmentDate': 'Tue, Dec 12 • 10:00 AM',
      'online': 'Online',
      'inPerson': 'In Person',
      'noData': 'No data available',
      'passwordResetSent': 'Password reset email sent! Check your inbox.',
      'missedAppointments': 'Missed Appointments',
      'upcomingFollowUps': 'Upcoming Follow-ups',
      'noFollowUps': 'No upcoming follow-ups',
      'bodyTemp': 'Body Temp',
      'yourDoctor': 'Your Doctor',
      'noDoctorAssigned': 'No doctor assigned yet',
      'noDoctorAssignedDesc':
          'Your care team will be shown here once assigned.',
      'noPatientsAssigned': 'No patients assigned yet.',
      'noConversations':
          'No conversations yet.\nStart chatting from the Patients tab!',
      'appointmentConfirmed': 'Appointment Confirmed',
      'appointmentCancelled': 'Appointment Cancelled',
      'appointmentCompleted': 'Appointment Completed',
      'newMessage': 'New Message',
      'newAppointment': 'New Appointment',
      'appointmentScheduledNotif': 'You have a new appointment scheduled',
      'appointmentConfirmedNotif': 'Your appointment has been confirmed',
      'appointmentCancelledNotif': 'Your appointment has been cancelled',
      'confirm': 'Confirm',
      'confirmed': 'Confirmed',
      'cancelled': 'Cancelled',
      'scheduled': 'Scheduled',
      'completed': 'Completed',
      'serverDownTitle': 'Our servers are taking a short break',
      'serverDownDesc': 'We\'re fixing the issue. Auto-refreshing...',
      'reconnecting': 'Reconnecting...',
      'reconnectingSuccess': 'Reconnected successfully!',
      'noInternetTitle': 'No Internet Connection',
      'noInternetDesc': 'Please check your network settings and try again.',
    },
    'ar': {
      'appName': 'هيلث سينك',
      'getStarted': 'ابدأ الآن',
      'onboardingTitle': 'صحتك بين يديك',
      'onboardingSubtitle':
          'راقب علاماتك الحيوية، أدر سجلاتك، وتواصل مع الأطباء بسهولة.',
      'login': 'تسجيل الدخول',
      'createAccount': 'إنشاء حساب',
      'accessAccount': 'تفضل بالدخول إلى حسابك',
      'emailAddress': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'fullName': 'الاسم الكامل',
      'medicalLicense': 'رقم الترخيص الطبي',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'orLoginWith': 'أو سجل الدخول بواسطة',
      'or': 'أو',
      'continueWithGoogle': 'المتابعة مع جوجل',
      'processingLogin': 'جاري تسجيل الدخول...',
      'creatingAccount': 'جاري إنشاء الحساب...',
      'patient': 'مريض',
      'doctor': 'طبيب',
      'enterEmail': 'يرجى إدخال البريد الإلكتروني',
      'validEmail': 'يرجى إدخال بريد إلكتروني صحيح',
      'enterPassword': 'يرجى إدخال كلمة المرور',
      'passwordLength': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'passwordLength8': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
      'confirmPasswordReq': 'يرجى تأكيد كلمة المرور',
      'passwordsNoMatch': 'كلمتا المرور غير متطابقتين',
      'enterName': 'يرجى إدخال الاسم الكامل',
      'enterLicense': 'يرجى إدخال رقم الترخيص',
      'resetPassword': 'استعادة كلمة المرور',
      'resetPasswordDesc':
          'أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
      'sendResetLink': 'إرسال رابط الاستعادة',
      'hello': 'مرحبًا',
      'dashboard': 'الرئيسية',
      'vitals': 'العلامات الحيوية',
      'assistant': 'المساعد',
      'profile': 'الملف الشخصي',
      'myProfile': 'ملفي الشخصي',
      'currentHealthStatus': 'الحالة الصحية الحالية',
      'normal': 'طبيعي',
      'warning': 'تحذير',
      'critical': 'حرج',
      'heartRate': 'نبض القلب',
      'bloodOxygen': 'الأكسجين',
      'bloodPressure': 'ضغط الدم',
      'nextFollowUp': 'الموعد القادم',
      'seeAll': 'عرض الكل',
      'vitalsComingSoon': 'سجل العلامات الحيوية (قريباً)',
      'view': 'عرض',
      'needAttention': 'تحتاج انتباه',
      'criticalAlert': 'تنبيه حرج',
      'patientsNeedAttention': 'مريض يحتاج اهتمامًا فوريًا',
      'settings': 'الإعدادات',
      'medicalHistory': 'السجل الطبي',
      'privacySecurity': 'الخصوصية والأمان',
      'helpSupport': 'المساعدة والدعم',
      'guestUser': 'مستخدم زائر',
      'noEmail': 'لا يوجد بريد إلكتروني',
      'notifications': 'الإشعارات',
      'notificationsDesc': 'تلقي التنبيهات والتذكيرات',
      'language': 'اللغة',
      'logout': 'تسجيل الخروج',
      'logoutConfirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'notificationsTitle': 'الإشعارات',
      'noNotifications': 'لا توجد إشعارات جديدة',
      'markAllRead': 'تحديد الكل كمقروء',
      'doctorChatTitle': 'محادثة مع د. سارة',
      'typeDoctorMessage': 'اكتب رسالتك...',
      'doctorResponse':
          'مرحباً! لقد استلمت رسالتك. سأتحقق من علاماتك الحيوية وأعود إليك قريباً.',
      'chat': 'محادثة',
      'doctorDashboard': 'لوحة الطبيب',
      'myPatients': 'مرضاي',
      'totalPatients': 'إجمالي المرضى',
      'pendingMessages': 'رسائل معلقة',
      'todayAppointments': 'مواعيد اليوم',
      'recentPatients': 'المرضى الأخيرين',
      'searchPatients': 'ابحث عن مريض...',
      'viewPatient': 'عرض المريض',
      'sendMessage': 'إرسال رسالة',
      'patientDetails': 'تفاصيل المريض',
      'lastUpdate': 'آخر تحديث',
      'typePatientMessage': 'اكتب رسالة للمريض...',
      'vitalsHistory': 'سجل العلامات الحيوية',
      'assignPatient': 'تعيين مريض',
      'searchByNameOrPhone': 'ابحث بالاسم أو رقم الهاتف...',
      'searchByNameLabel': 'بالاسم',
      'searchByPhoneLabel': 'بالهاتف',
      'searchByNameHint': 'أدخل اسم المريض...',
      'searchByPhoneHint': 'أدخل رقم الهاتف...',
      'assign': 'تعيين',
      'noResults': 'لم يتم العثور على مرضى',
      'patientAssigned': 'تم تعيين المريض بنجاح!',
      'alreadyAssigned': 'المريض معين لك بالفعل',
      'connectionError':
          'خطأ في الاتصال. يرجى التحقق من الإنترنت والمحاولة مرة أخرى.',
      'serverError': 'خطأ في الخادم. يرجى المحاولة مرة أخرى لاحقاً.',
      'unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
      'phone': 'هاتف',
      'retry': 'إعادة المحاولة',
      'searching': 'جاري البحث...',
      'typeToSearch': 'اكتب اسم أو رقم هاتف للبحث',
      'removePatient': 'إزالة المريض',
      'removePatientConfirm':
          'هل أنت متأكد أنك تريد إزالة هذا المريض من قائمتك؟',
      'removePatientSuccess': 'تم إزالة المريض بنجاح',
      'removePatientError': 'فشل في إزالة المريض. يرجى المحاولة مرة أخرى.',
      'remove': 'إزالة',
      'conditions': 'الحالات المرضية',
      'medications': 'الأدوية',
      'allergies': 'الحساسية',
      'procedures': 'العمليات',
      'diagnosed': 'تاريخ التشخيص',
      'dosage': 'الجرعة',
      'frequency': 'التكرار',
      'since': 'منذ',
      'active': 'نشط',
      'ongoing': 'مستمر',
      'controlled': 'تحت السيطرة',
      'seasonal': 'موسمي',
      'asNeeded': 'عند الحاجة',
      'severe': 'شديد',
      'mild': 'خفيف',
      'allergen': 'المادة المسببة',
      'reaction': 'رد الفعل',
      'assistantTitle': 'مساعد هيلث سينك',
      'typeMessage': 'اكتب أعراضك...',
      'urgentWarning': 'عاجل: اتصل بخدمات الطوارئ الآن',
      'welcomeMessage':
          'مرحباً! أنا مساعد هيلث سينك. كيف يمكنني مساعدتك اليوم؟',
      'emergencyResponse':
          'بناءً على أعراضك، قد يكون هذا خطيراً. يرجى الرجوع إلى لافتة الطوارئ أعلاه.',
      'generalResponse': 'أفهم ذلك. هل يمكنك إخباري بالمزيد؟',
      'success': 'تم بنجاح!',
      'error': 'خطأ!',
      'info': 'معلومة',
      'drSarahJohnson': 'د. سارة جونسون',
      'drAhmedHassan': 'د. أحمد حسن',
      'drSaraMohamed': 'د. سارة محمد',
      'drOmarAli': 'د. عمر علي',
      'drFatimaYoussef': 'د. فاطمة يوسف',
      'appointmentDate': 'الثلاثاء، 12 ديسمبر • 10:00 ص',
      'online': 'عن بُعد',
      'inPerson': 'حضوري',
      'noData': 'لا توجد بيانات',
      'passwordResetSent':
          'تم إرسال رابط استعادة كلمة المرور! تحقق من بريدك.',
      'missedAppointments': 'المواعيد الفائتة',
      'upcomingFollowUps': 'المواعيد القادمة',
      'noFollowUps': 'لا توجد مواعيد قادمة',
      'bodyTemp': 'حرارة الجسم',
      'yourDoctor': 'طبيبك',
      'noDoctorAssigned': 'لا يوجد طبيب معين بعد',
      'noDoctorAssignedDesc':
          'سيظهر فريق الرعاية الخاص بك هنا بمجرد التعيين.',
      'noPatientsAssigned': 'لا يوجد مرضى معينين بعد.',
      'noConversations':
          'لا توجد محادثات بعد.\nابدأ المحادثة من تاب المرضى!',
      'appointmentConfirmed': 'تم تأكيد الموعد',
      'appointmentCancelled': 'تم إلغاء الموعد',
      'appointmentCompleted': 'تم إكمال الموعد',
      'newMessage': 'رسالة جديدة',
      'newAppointment': 'موعد جديد',
      'appointmentScheduledNotif': 'لديك موعد جديد تم جدولته',
      'appointmentConfirmedNotif': 'تم تأكيد موعدك',
      'appointmentCancelledNotif': 'تم إلغاء موعدك',
      'confirm': 'تأكيد',
      'confirmed': 'مؤكد',
      'cancelled': 'ملغي',
      'scheduled': 'مجدول',
      'completed': 'مكتمل',
      'serverDownTitle': 'خوادمنا في فترة راحة قصيرة',
      'serverDownDesc': 'نحن نعمل على إصلاح المشكلة. جاري التحديث التلقائي...',
      'reconnecting': 'جاري إعادة الاتصال...',
      'reconnectingSuccess': 'تم إعادة الاتصال بنجاح!',
      'noInternetTitle': 'لا يوجد اتصال بالإنترنت',
      'noInternetDesc': 'يرجى التحقق من إعدادات الشبكة والمحاولة مرة أخرى.',
    },
  };

  /// Get a localized string by key.
  String get(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
